allowBuilds:
  '@firebase/util': false
  '@nestjs/core': false
  '@prisma/engines': false
  bcrypt: false
  msgpackr-extract: false
  prisma: false
  protobufjs: false
  unrs-resolver: false
onlyBuiltDependencies:
  - prisma
  - "@prisma/engines"
  - bcrypt
  - "@nestjs/core"
  - "@firebase/util"
  - msgpackr-extract
  - protobufjs
  - unrs-resolver
